name: malody_catch_editor
description: Malody Catch 制谱器
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  archive: ^3.4.10
  path: ^1.9.0
  desktop_drop: ^0.4.4
  just_audio: ^0.9.36